{{- if not .Values.newrelic.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newrelic-exporter.fullname" . }}
  labels:
    {{- include "newrelic-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.newrelic.apiKey | b64enc | quote }}
{{- end }}
